# Generated by Django 4.2 on 2023-04-08 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='featured_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.student'),
        ),
    ]
